### ISSUE TITLE
CI/CD: Automate version bumps

### ISSUE THREAD

**Issue by yvesgurcan** [yvesgurcan/web-midi-player#107]
This will require to create a custom GitHub Action forked from `paulhatch/semantic-version` that takes a `github_token`.

```
            - name: Version bump
              uses: paulhatch/semantic-version@v2
              with:
                branch: ${{ github.head_ref }}
                # A string which, if present in a git commit, indicates that a change represents a major change
                major_pattern: "(MAJOR)"
                # Same as above except indicating a minor change
                minor_pattern: "(MINOR)"
                # A string to determine the format of the version output
                format: "${major}.${minor}.${patch}"
                github_token: ${{ secrets.GITHUB_TOKEN }}
```
